// <auto-generated />
using System;
using Eldorado.TeamManager.DataAccess.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eldorado.TeamManager.DataAccess.Migrations
{
    [DbContext(typeof(TeamManagerDbContext))]
    [Migration("20230321082032_DataSkill")]
    partial class DataSkill
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Eldorado.TeamManager.Domain.Entities.Collaborator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Collaborators");
                });

            modelBuilder.Entity("Eldorado.TeamManager.Domain.Entities.CollaboratorSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long>("CollaboratorId")
                        .HasColumnType("bigint");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("SkillId");

                    b.ToTable("CollaboratorSkills");
                });

            modelBuilder.Entity("Eldorado.TeamManager.Domain.Entities.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 101L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "C#",
                            Type = 2
                        },
                        new
                        {
                            Id = 102L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "JavaScript",
                            Type = 2
                        },
                        new
                        {
                            Id = 103L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Java",
                            Type = 2
                        },
                        new
                        {
                            Id = 104L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Python",
                            Type = 2
                        },
                        new
                        {
                            Id = 105L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "PHP",
                            Type = 2
                        },
                        new
                        {
                            Id = 106L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "VisualBasic",
                            Type = 2
                        },
                        new
                        {
                            Id = 107L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "C",
                            Type = 2
                        },
                        new
                        {
                            Id = 108L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "C++",
                            Type = 2
                        },
                        new
                        {
                            Id = 109L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "SQL",
                            Type = 2
                        },
                        new
                        {
                            Id = 110L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "PL/SQL",
                            Type = 2
                        },
                        new
                        {
                            Id = 111L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "T-SQL",
                            Type = 2
                        },
                        new
                        {
                            Id = 112L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Delphi",
                            Type = 2
                        },
                        new
                        {
                            Id = 113L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "FoxPro",
                            Type = 2
                        },
                        new
                        {
                            Id = 114L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Oracle",
                            Type = 1
                        },
                        new
                        {
                            Id = 115L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "SQL Server",
                            Type = 2
                        },
                        new
                        {
                            Id = 116L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "PostgreSQl",
                            Type = 2
                        },
                        new
                        {
                            Id = 117L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "MySQL",
                            Type = 2
                        },
                        new
                        {
                            Id = 118L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Firebird",
                            Type = 2
                        },
                        new
                        {
                            Id = 119L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "MongoDB",
                            Type = 2
                        },
                        new
                        {
                            Id = 120L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "RavenDB",
                            Type = 2
                        },
                        new
                        {
                            Id = 121L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Docker",
                            Type = 6
                        },
                        new
                        {
                            Id = 122L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Kubernetes",
                            Type = 6
                        },
                        new
                        {
                            Id = 123L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Ansible",
                            Type = 6
                        },
                        new
                        {
                            Id = 124L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "GitLab",
                            Type = 6
                        },
                        new
                        {
                            Id = 125L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "GitHub",
                            Type = 6
                        },
                        new
                        {
                            Id = 126L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Adm Windows",
                            Type = 6
                        },
                        new
                        {
                            Id = 127L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Adm Linux",
                            Type = 6
                        },
                        new
                        {
                            Id = 128L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Azure",
                            Type = 6
                        },
                        new
                        {
                            Id = 129L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "AWS",
                            Type = 6
                        },
                        new
                        {
                            Id = 130L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Google Cloud",
                            Type = 6
                        },
                        new
                        {
                            Id = 131L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Oracle Cloud",
                            Type = 6
                        },
                        new
                        {
                            Id = 132L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "SonarQube",
                            Type = 3
                        },
                        new
                        {
                            Id = 133L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Black Duck",
                            Type = 3
                        },
                        new
                        {
                            Id = 134L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Pacote Office",
                            Type = 3
                        },
                        new
                        {
                            Id = 135L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Jira",
                            Type = 3
                        },
                        new
                        {
                            Id = 136L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Trello",
                            Type = 3
                        },
                        new
                        {
                            Id = 137L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "TFS",
                            Type = 3
                        },
                        new
                        {
                            Id = 138L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Figma",
                            Type = 3
                        },
                        new
                        {
                            Id = 139L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "ASP.NET",
                            Type = 4
                        },
                        new
                        {
                            Id = 140L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Spring Boot",
                            Type = 3
                        },
                        new
                        {
                            Id = 141L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Angular",
                            Type = 3
                        },
                        new
                        {
                            Id = 142L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "VueJS",
                            Type = 3
                        },
                        new
                        {
                            Id = 143L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "React",
                            Type = 3
                        },
                        new
                        {
                            Id = 145L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "SCRUM",
                            Type = 5
                        },
                        new
                        {
                            Id = 146L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "PMBOK",
                            Type = 5
                        },
                        new
                        {
                            Id = 147L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "EXtreme programming",
                            Type = 5
                        },
                        new
                        {
                            Id = 148L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a dolor nec nisl volutpat finibus.",
                            Name = "Kanban",
                            Type = 5
                        });
                });

            modelBuilder.Entity("Eldorado.TeamManager.Domain.Entities.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathAvatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Eldorado.TeamManager.Domain.Entities.TeamCollaborator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long>("CollaboratorId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamCollaborators");
                });

            modelBuilder.Entity("Eldorado.TeamManager.Domain.Entities.TeamSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamSkills");
                });

            modelBuilder.Entity("Eldorado.TeamManager.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirsName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Eldorado.TeamManager.Domain.Entities.CollaboratorSkill", b =>
                {
                    b.HasOne("Eldorado.TeamManager.Domain.Entities.Collaborator", "Collaborator")
                        .WithMany("CollaboratorSkills")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldorado.TeamManager.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Eldorado.TeamManager.Domain.Entities.TeamCollaborator", b =>
                {
                    b.HasOne("Eldorado.TeamManager.Domain.Entities.Collaborator", "Collaborator")
                        .WithMany()
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldorado.TeamManager.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Eldorado.TeamManager.Domain.Entities.TeamSkill", b =>
                {
                    b.HasOne("Eldorado.TeamManager.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldorado.TeamManager.Domain.Entities.Team", "Team")
                        .WithMany("TeamSkills")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Eldorado.TeamManager.Domain.Entities.Collaborator", b =>
                {
                    b.Navigation("CollaboratorSkills");
                });

            modelBuilder.Entity("Eldorado.TeamManager.Domain.Entities.Team", b =>
                {
                    b.Navigation("TeamSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
